spring.application.name=cpcc

# Datasource configuration (to be filled)
spring.datasource.url=jdbc:mysql://localhost:3306/cpcc
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.thymeleaf.cache=false

# Internationalization
spring.messages.basename=messages
spring.web.locale=fr
spring.web.locale-resolver=fixed
